### ISSUE TITLE
DSC.ps1 Requires module nRoboCopy

### ISSUE THREAD

**Issue by mattmcnabb** [Cidney/Cidney#1]
The requires statement in the DSC.ps1 file includes the module "nRoboCopy" which is unknown and I can't seem to find anywhere that it's actually used. Is this module really needed? If so, where does one get it and can it simply be included in the Cidney module?

**Comment by RobertKozak** [comment]
Sorry about that. It was a left over of a class based DSC Resource I was using for testing. That statement came from ISESteriods being too aggressive in adding that statement. I have removed it and updated the repo.
