### ISSUE TITLE
Defining Dependancies

### ISSUE THREAD

**Issue by cdhunt** [Cidney/Cidney#5]
How would I prevent a Stage from running if a previous stage "fails"?

**Comment by RobertKozak** [comment]
It should stop executing if it encounters an exception. 
Do you have a sample in which this is not the case?

**Comment by cdhunt** [comment]
Same example as issue #4. Stage `BuildConfig` is running even if there are errors in `CloneSource`.

**Comment by RobertKozak** [comment]
Ok I'll look into it again. I might have another version I didn't commit yet

**Comment by RobertKozak** [comment]
This should be fixed in the latest commit. Let me know and if ok I will republish to Powershell Gallery

**Comment by cdhunt** [comment]
Yes, it appears my pipeline stops at CloneSource if an error is encountered.
